import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Link from "next/link";

import styles from "./rootStyles.module.css";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <header className={styles.header}>
          <h2>
            <Link className={styles.homeLink} href={"/home"}>
              Globo
            </Link>
          </h2>
          <h2>
            <Link className={styles.menuBarLink} href={"/settings"}>
              Settings
            </Link>
          </h2>
          <h2>
            <Link className={styles.menuBarLink} href={"/blog"}>
              Blog
            </Link>
          </h2>
          <h2>
            <Link className={styles.menuBarLink} href={"/conference"}>
              Conference
            </Link>
          </h2>
        </header>
        {children}
      </body>
    </html>
  );
}
